{% set name = "AnnexRemote" %}
{% set version = "1.4.4" %}
{% set sha256 = "6452e79a2fe67ca70761cd462a5a85ed5af784c4c06d337f7452ef5b168479b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lykos153/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-added-listconfigs.patch

build:
  skip: true  # [not linux]
  number: 0

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
