{% set name = "AnnexRemote" %}
{% set version = "1.5.0" %}
{% set sha256 = "81046f80217f70c2f1f49e0af1d7da9b414cc9c047b6e2c41deac7118fcaa601" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/Lykos153/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-added-listconfigs.patch

build:
  skip: True  # [not linux]
  number: 1

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  imports:
    - annexremote
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
