{% set name = "AnnexRemote" %}
{% set version = "1.4.1" %}
{% set sha256 = "e9e35f6f00f39c78566b57f45fc5235a91644bf19ae798c633a82ee93d8d0520" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/Lykos153/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [not linux]
  number: 0

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
