{% set name = "AnnexRemote" %}
{% set version = "v1.2.1_alpha.2" %}
{% set sha256 = "8a42e193196b5e96cfe1bcbd284b4713f3010127e89f9a66b53512c89f71e04c" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/notestaff/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - six
    - python
  run:
    - six
    - python

test:
  requires:
    - nose
  commands:
    - nosetests -v
    - python -c "from annexremote import Master, SpecialRemote, RemoteError"
  imports:
    - annexremote

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
