{% set name = "AnnexRemote" %}
{% set version = "1.6.1" %}
{% set sha256 = "189670b74ca30440a7edc47ce28e6501958f4480a0fbbba4ef090fb38fa43cac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lykos153/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-added-listconfigs.patch
    - 0001-BF-TST-match-newer-pythons-exception-to-include-the-.patch

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  imports:
    - annexremote
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
