{% set name = "annexremote" %}
{% set version = "1.6.6" %}
{% set sha256 = "5f78d0753c0763d95fc4c52050bd6212bb32457d32f6575dc66a83178e0283a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - annexremote
  source_files:
    - tests/
    - examples/
  requires:
    - pytest
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - jwodder
