{% set name = "AnnexRemote" %}
{% set version = "v1.2.1a3" %}
{% set sha256 = "131aa71e84df0ab08f05f15ee8eac27cf3d3fc914a5ef78553173d61eca42c9d" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/notestaff/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - pip
    - six
    - python
  run:
    - six
    - python

test:
  requires:
    - nose
    - git-annex
    - coreutils
    - wget
    - curl
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
