{% set name = "AnnexRemote" %}
{% set version = "1.3.1a1" %}
{% set sha256 = "c56a56bea994a44497851b964af81ab1510d33c401c0a344a0f37b6a8e1fb857" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/notestaff/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [not linux]
  number: 1000

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
