{% set name = "AnnexRemote" %}
{% set version = "1.5.0" %}
{% set sha256 = "92f32b6f5461cbaeefe0c60b32f9c1e0c1dbe4e57b8ee425affb56f4060f64ef" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}
  patches:
    - 0001-added-listconfigs.patch

build:
  skip: True  # [not linux]
  number: 0

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  imports:
    - annexremote
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
