{% set name = "AnnexRemote" %}
{% set version = "1.2.1a6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/notestaff/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 608c341a1a343b35603526de557fc533dc1a85ef1dde86808fa4c9161ade5e56

build:
  skip: True  # [not unix]
  number: 1001

requirements:
  host:
    - pip
    - python
    - future
    - nose
    - mock
  run:
    - python
    - future

test:
  requires:
    - nose
    - mock
    - git-annex  # [linux]
    - gnupg  # [linux]

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
