{% set name = "AnnexRemote" %}
{% set version = "1.2.1_alpha.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/notestaff/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 596d24cf7ea6ace7e3719e9e31726e8d726512101a4d0aec58324090a51dad2e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - six
    - python
  run:
    - six
    - python

test:
  requires:
    - nose
  commands:
    - nosetests -v
    - python -c "from annexremote import Master, SpecialRemote, RemoteError"
  imports:
    - annexremote

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
