{% set name = "annexremote" %}
{% set version = "1.6.5" %}
{% set sha256 = "ad0ccdd84a8771ad58922d172ee68b225ece77bf464abe4d24ff91a4896a423e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not linux]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - annexremote
  source_files:
    - tests/
    - examples/
  requires:
    - pytest
    - git
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GPL-3.0-only
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - jwodder
