{% set name = "AnnexRemote" %}
{% set version = "1.4.0" %}
{% set sha256 = "50472e1232a45afef19d86aa0c19043c5468b0875c87fc2387c8983dfb5e68a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lykos153/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not linux]
  number: 0

requirements:
  host:
    - pip
    - python
    - future
  run:
    - python
    - future

test:
  source_files:
    - tests/
    - examples/
  requires:
    - nose
    - mock
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
