{% set name = "annexremote" %}
{% set version = "1.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2db60f428999fe2ad9a18c03feb94829ec88144279cb5630b77d62138cff3511

build:
  noarch: python
  number: 1

requirements:
  host:
    - pip
    - python >=3
    - nose
  run:
    - python >=3

test:
  requires:
    - nose
    - git-annex
    - gnupg

about:
  home: https://github.com/Lykos153/AnnexRemote
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Python library for implementing git-annex external special remotes
  dev_url: https://github.com/Lykos153/AnnexRemote

extra:
  recipe-maintainers:
    - notestaff
