appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: S3Oa6vYCFrnVjjpOGd212xSF98kBYiSdgd905caThiOaPjufP1zdLzJgd0S4PVRiLF/4DnL7XxFMhSoPwAe2ecotBKwnZbBiYpS0dPp4nkJtG1TccqiaCUY9xi4I2lEogvZ8B8yUge9n51UYOUaaOkqBLup1AtRM9yvJs4a6HHJuDPevZ2HAjAgf8djBh12uqRQAhUN8YJCCnT7tQdMldrq7F0jgUU21+MuuOQDAB57ATWWqgzuvUonN1wpGcp87VkJkqv6eUPWimY2eZ46fCzUk6b+Rloxiz/OOWG7W5oDKjMZNNa0wNDM45HbR5bywBoQY7xU75lBsRKSwUW38PHtnyvN6IeZRIS1fKbTQinAuB4MIIyexjBcq0sOn5F4w2e1+uVspDL4Wsy9SwVe0WZQIT0M6n5+0bLhV0zzXdlNVIdZtWGJ/Q5rw4V3j4IB8NUW87x0f6XsQkuQB/carZY9CitOYyCBgZIbA9ieni38KW7bdgmWMR4+Kb6qDjsEJJd6wCAnEgKDOxd0UVBj02Boi9D7KydEZXdQxyBFpRITFSHBVYCWmKPxSHUoqqkBsgezGl1o10xA7QleHD8asfaP+6jdZNh8T2i0ht7jo7N0hW8ZPbqsNMlnhStvth3mj4lG+oOKIoZ6Y+Q0HnQAKwz0hArOtCjN/ItHfw+A+4gg=}
